image: ruby:3.1.2

stages: 
    - build
    - test
    - deploy

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install
  
build:
  stage: build
  script:
  - ruby -v
  - echo "Hello, $GITLAB_USER_LOGIN!"
   
test:
  stage: test 
  script:
       - bundle exec rspec

deploy:
  stage: deploy
  script:  - gem install dpl
  - dpl --provider=heroku --app=url-shortener --api-key=0e2b9b7d-7014-45f9-8cf1-1e54b4086959

  environment: production

