image: ruby:3.1

stages: 
    - build
    - test
    - deploy

build:
  stage: build
  script:
         - rails s

test:
  stage: test 
  script:
       - bundle exec rspec

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production