image: ruby:3.1

stages: 
    - build
    - test
    - deploy

before_script:
     -gem install bundler
     -bundle install
  
build:
  stage: build
  script:
         - bundle exec rails assets:precompile

test:
  stage: test 
  script:
       - bundle exec rspec

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production