image: ruby:latest

variables:
  RUBY_VERSION: 3.1.2
  RAILS_VERSION: 7.0.3
  NODE_VERSION: 16.14.2

stages:
  - code-review
  - build
  - test
  - deploy

code-review:
  stage: code-review
  script:
    - apt-get update && apt-get install -y build-essential
    - gem install bundler
    - bundle install
    - yarn install
    - rails rake brakeman:run
    - rails rake rubocop:run
    - yarn run test:lint

build:
  stage: build
  script:
    - rails test
    - yarn run test:unit
    - yarn run test:integration
    - rails assets:precompile

test:
  stage: test
  script:
    - rails test:system

deploy:
  stage: deploy
  script:
    - rails deploy production

