image: ruby:3.1

stages: 
    - build
    - test
    - deploy

# before_script:
#      - apt-get update -qy
#      - apt-get install -y nodejs
#      - gem install bundler
#      - bundle install
  
build:
  stage: build
  script:
    - bundle install
    - yarn install
    - bin/rails assets:precompile
    - bin/rails test:prepare
    
test:
  stage: test 
  script:
       - bundle exec rspec

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production