image: ruby:3.1.2

variables:
   $HEROKU_APP_NAME: "url-shortener" 
   $HEROKU_PRODUCTION_KEY: "0e2b9b7d-7014-45f9-8cf1-1e54b4086959"

stages: 
    - build
    - test
    - deploy
    - production

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install
  - apt-get install yarn
  
build:
  stage: build
  script:
   - rails assets:precompile
    - rails css:build
    - rails css:install
   

test:
  stage: test 
  script:
       - bundle exec rspec

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production

