image: ruby:3.1.2

before_script:
  - apt-get update -qy
  - apt-get install -y nodejs
  - gem install bundler
  - bundle install
  
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test-job1:
  stage: test
  script:
     -  echo "this job tests something"

deploy:
  stage: deploy
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production